require("alexrp.plugins-setup")
require("alexrp.core.keymaps")
require("alexrp.core.colorscheme")
require("alexrp.core.options")
require("alexrp.plugins.comment")
require("alexrp.plugins.nvim-tree")
require("alexrp.plugins.lualine")
